Prevent accidental interpretation of `<A>` as HTML
steveklabnik/ref_slice pull request #6
Opened 2016-10-28 19:22 UTC by pthariensflame

Also add code font.

2016-10-28 20:36 UTC, steveklabnik requested changes

2016-10-28 20:36 UTC, steveklabnik commented on src/lib.rs
> +/// Converts a reference to `Option\<A\>` into a slice of length 0 or 1 (without copying).
With the backticks, the \s shouldn't be needed. Could you just include the graves please? Thanks!

2016-10-28 22:09 UTC, pthariensflame commented on src/lib.rs
> +/// Converts a reference to `Option\<A\>` into a slice of length 0 or 1 (without copying).
Ok!

2016-10-29 03:22 UTC, pthariensflame commented
@steveklabnik How does it look now?

2016-11-03 12:48 UTC, steveklabnik approved these changes

2016-11-03 12:48 UTC, merged

2016-11-03 12:48 UTC, steveklabnik commented
Thank you!